### ISSUE TITLE
Standard install, installs development version of druapl

### ISSUE THREAD

**Issue by misilot** [Islandora-Devops/claw-playbook#213]
When the standard install finishes the user currently gets a dev version of drupal? Should it not be at most the major release of drupal? 9.3.x currently,  not 9.4-dev?

<img width="628" alt="image" src="https://user-images.githubusercontent.com/1446856/162336713-02624a86-d24b-4b40-8cdd-fe68dd568d9f.png">

**Comment by rosiel** [comment]
I think it might have chnaged since you filed this, but there is a line in vars/standard.yml that says:

`drupal_composer_project_package: "drupal/recommended-project:^9@stable`

Each tagged release corresponds to a stable release of Drupal. So we should not get the dev stuff anymore, unless you (playbook runner) go into that vars file and change it.

Does this satisfy the issue?

**Comment by misilot** [comment]
Possibly. I'm gonna go with yes and close this anyways.
